src/domain/settings/regions/new.js

Multiplies tax_rate with 100 to convert to whole number percentage
The database saves percentages with a value between 0-100, so to visually show it as a decimal number, we have to account for this before we call the create endpoint
Multiplies tax_rate with 100 when calling the `create` endpoint

multiply value with 100 to convert to whole number percentage

---

src/domain/settings/regions/edit-shipping.js

**What**
- Allows to update a `Shipping Option` with new requirements, even if it had no prior requirements
**Why**
- It should be optional whether to add requirements to a `Shipping Option` and then possible to add requirements later, even if it was created without any.
**Note**
Dependency of [#340](https://github.com/medusajs/medusa/pull/340) in Medusa Core to take effect before the change will be supported.

fix: Edit shipping options requirements

---

src/domain/gift-cards/manage/index.js
src/utils/prices.js

**What?**
- Correct denomination creation for giftcards
- Routing to product page of giftcards after creation
- Adjusted denomination amount to reflect the decimal representation of prices in the database
**Why?**
- Giftcard creation crashed previously
- After creation the client navigated to `product/undefined`
**How?**
- Changed field name to use object notation for index as described in useFieldArray documentation
- Included a key for each denomination
- Created a util method for price calculation when sending data to the database for easy inclusion of additional 'no division currencies' or later changes to price calculations

Bug: include denominations on giftcard creation

---

src/services/request.js

**What**
- Updates the STORE_URL default value to be inline with the default medusa-default-starter port.

fix: update STORE_URL to default medusa port

---

src/domain/orders/details/claim/create.js
src/domain/orders/details/returns/index.js
src/domain/orders/details/swap/create.js
src/domain/orders/details/utils/create-filtering.js

**What?**
- Improved consistency in the creation of claims, swaps and refund requests
- Ensured that the right quantity of an item can be refunded, swapped or claimed 
- Refactored filtering of quantities and items to ensure a uniform experience
**Why?**
- Previously the ordered quantities was shown after claims and swaps
**How?**
- Add all additional items and lineitems to a map
- iterate all claims, removing items that have been claimed
**Testing**
- Manual testing

Bug:order timeline item inconsistencies

---

src/components/dropdown/index.js
src/components/modal/index.js
src/components/react-select/index.js
src/domain/orders/details/claim/create.js
src/domain/orders/details/swap/create.js
src/domain/orders/new/components/items.js
src/domain/orders/new/index.js
src/domain/orders/new/new-order.js

- Changing dropdowns (`dropdown` and `react-select` components) are on top of modals (and other things). 
- These sometimes overflow the modal resulting in the user needing to scroll to select input. This is a nuisance for the user.
- Wrap the `dropdown`'s `scrollable` so that itss absolute position is respected. Ensure that `menuPortalTarget` is always set to `document.body` for the `react-select` and that this is closed on resizing as to avoid random floating behaviour of the `scrollable`.

fix: dropdowns on top

---

src/components/sidebar/index.js

- Only allow one category to ever be expanded at once in the sidebar, and only collapse this when another element is expanded.
- To reduce clutter and ease of use
- Implement custom trigger behaviour and apply this to all collapsables. (Cannot generate custom function component to increase reuse as this removes the animations) Also, this includes wrapping elements without subitems in a collapsible.

Fix: expandable sidebar issues

---

src/components/variant-grid/index.js
src/domain/products/details/variants/index.js
src/domain/products/details/variants/variant-editor.js

- Fix: when trying to copy a variant, when cancel is clicked, a variant gets removed
- Slightly enhances the ux by reducing "save points": all changes occurring either in the grid or through the edit variant modal are only sent to our backend when the user clicks on the Save button
- Allow removal of weight, height, width, and length fields
- Better UX
###How
- Transform number fields from empty string to null before making a POST request
- Keep variants state in sync with the changes from the grid and the variant modals (copy + edit)

fix: product details variants

---

package.json
src/domain/products/new/index.js
yarn.lock

While working on the Gatsby theme we are creating for the admin, we noticed that `lodash` was not included in the package dependencies, and it was not imported in `src/domain/products/new/index.js`.
In this PR, I've added `lodash` to the dependencies and added the missing import.

fix: add missing lodash dependency

---

src/domain/products/details/variants/index.js

Fix for https://github.com/medusajs/admin/issues/180
Why? inventory_quantity is being sent as a String whilst a number type is required hence a 400 upon saving a product.

Fix inventory quantity

---

src/domain/orders/details/index.js

Show controls for cancel/save notes in the timeline of the orders. This solves the issue #154.
In the current version, is impossible to cancel the notes and the options are blocked until you write a note.
The two buttons were added, the function of `handleCancelNote` was already in the code but never implemented.
I tested canceling the note, adding the note with the save button, and pressing enter.

Fix: Add cancel save in timeline notes

---

.gitignore
src/components/image-upload/index.js

Probably some other place could contains those kind of error. The usage of typescript could prevent that 👍

Fix() image upload missing event argument

---

src/domain/orders/details/index.js

Hi, this is my solution for the issue #195 
In the past, when we consulted the details of an order
When we checked the payment overview
In the sum, those swaps that were canceled were considered. This should not be like that. My solution was to add a filter to exclude those swaps canceled when we make the map for the sum.
Please let me know if there is anything I can improve :)

Hide canceled swaps from payment sum

---

src/assets/styles/global.css
src/components/fundamentals/button/index.tsx
src/components/molecules/modal/index.tsx
src/components/organisms/delete-prompt.tsx

**What**
- add a danger button to button component and `global.css`
- fix modal widths
- Add delete prompt 
Delete promp has the following properties: 
- `heading: string`: heading for the prompt ie. 'Remove user'
- `text: string`: text for prompt body ie. 'Are you sure you want to remove this user?'
- `successText?: string`: success text for toaster
- `handleClose: () => void`: close function for modal
- `onDelete: () => Promise<void>`: function which deletes the entity in question

Feat: Revamp delete prompt

---

src/components/organisms/body-card.tsx
src/domain/settings/personal-information.tsx

Add `className` prop to `BodyCard` to allow for custom styling.
Example use-case:
If the `<BodyCard/>` inside the two-split pane should not always span full height but fit its content until content expands the view, we can set the height to `h-auto` and `max-h-full`.

Allow control of BodyCard styling

---

src/components/organisms/body-card.tsx
src/components/templates/layout.tsx
src/components/templates/two-split-pane.tsx
src/domain/settings/personal-information.tsx
src/hooks/use-computed-height.ts
src/hooks/use-window-dimensions.ts

Both children should have the same height, or in other words, the smaller sibling should follow the larger sibling in terms of height
**Before**
Right pane's height is not equal to left pane's height
**After**
Right pane's height is equal to left pane's height
When the content grows beyond a certain height, it overflows the bottom padding initially set by the layout
**Before**
There is no bottom padding when the page is scrolled all the way
**After**
- ensures consistency
- **two split pane**: use grid layout as opposed to flex layout. When screen size > medium, we use a 2-column layout, otherwise, we only use one column. 
- **layout**: 
- remove `height: 100%` from our Layout component's `main` tag and use the default `height: auto` so that it grows with the content.
- replace …

fix: two split pane + layout

---

package.json
src/assets/styles/global.css
src/components/fundamentals/input-container.tsx
src/components/molecules/input/input.stories.tsx
src/components/molecules/textarea/index.tsx
src/components/molecules/textarea/textarea.stories.tsx
tailwind.config.js
yarn.lock

- adds textarea 
- adds a story for textarea
- fixes typescript errors + prettier for `InputContainer` and `input.stories.tsx`
- used @pKorsholm's work on `Input` as reference
- used `@tailwindcss/line-clamp` (thanks @kasperkristensen!) and extended it with a custom class to allow for dynamic values in `line-clamp` based on textarea's `rows` value
_Note: clamping the multiline textarea works by using the [line-clamp css property](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp). I noticed some issues with it when using Firefox, but as far as I have tried, it works well with Chrome and Brave. So please if you have Safari/Firefox, try to run it there and see if the clamping behaves as expected._

feat: revamp textarea

---

.storybook/preview-head.html
package.json
src/components/atoms/tooltip/index.tsx
src/components/atoms/tooltip/tooltip.stories.tsx
src/components/fundamentals/icons/alert-icon/alert-icon.stories.tsx
src/components/fundamentals/icons/alert-icon/index.tsx
src/components/fundamentals/icons/info-icon/index.tsx
src/components/fundamentals/icons/info-icon/info-icon.stories.tsx
src/components/fundamentals/input-header.tsx
src/components/molecules/info-tooltip/index.tsx
src/components/molecules/info-tooltip/info-tooltip.stories.tsx
src/components/molecules/input/index.tsx
src/components/molecules/input/input.stories.tsx
src/components/organisms/sidebar/sidebar.stories.tsx
yarn.lock

- adds a generic tooltip component
- adds an info tooltip component (a tooltip which has an info icon as a trigger)
- adapts the `Input` component to use an info tooltip next to its label
- adds info + alert icons and their stories
- adds stories for tooltips
- adds a story for info tooltip
- adds a story for an input with tooltip
- adds a story for an input with custom tooltip
-  uses Radix's tooltip component

add: tooltip + stories + adapt input

---

package.json
src/components/organisms/details-collapsible/details-collapsible.stories.tsx
src/components/organisms/details-collapsible/index.tsx
yarn.lock

**What**
Adds a collapsible organism for showing/hiding details.
**How**
Use `@radix-ui/collapsible`
Decided to add this as an organism, since it's already being used multiple times in the design. Considered adding a more generic collapsible molecule, but Radix UI's collapsible is already quite customizable, so did not find this relevant. Alternatively, we could also completely remove this component and use Radix directly. Let me know, what you think :)

feat: DetailsCollapsible

---

src/components/molecules/actionables.tsx
src/components/organisms/body-card.tsx
src/domain/settings/regions/index.tsx
yarn.lock

**What**
- Adds the ability to force a dropdown menu on Actionables. This is controlled by setting `forceDots` on Actionables (defaults to false). This can also be set on BodyCard by setting `forceDropdown`
- Allows to provide a customTrigger on Actionables (and BodyCard), controlled by setting `customTrigger` to a ReactNode such as `<button onClick={() => console.log("custom")}>Custom Button</button>`. This is controlled on BodyCards by setting `customActionable`.

fix: custom actionables

---

src/components/organisms/edit-denominations-modal/index.tsx

- strip denominations from `indexId` when submitting 
@olivermrbl dammit I missed this bad boi :disappointed:

fix: strip denominations from indexId

---

src/pages/login.tsx

**What changes are in the PR?**
Changed the redirection logic to go to `/a/orders` after login
**Why these changes are relevant?**
So, after login user will not be redirected to an empty screen
**How have the changes been implemented?**
Added `/orders` onSuccess of login
**How has the changes been tested or how can the reviewer test the feature?**
Login to the admin ->  Verify that you are on the orders page and not on an empty page

Fixed: the issue of redirecting to orders page after login(#298)

---

src/components/molecules/table/index.tsx
src/components/templates/gift-card-table/index.tsx
src/hooks/use-highlight-search.tsx

**What**
- Adds hook for highlighting search terms in tables

feat: add hook to highlight search terms

---

src/components/molecules/sidebar-team-member/index.tsx

**What** 
- add `bg-inherit` to sidebar team member to prevent visual bug in tables and with other hover effects(bg was previously `bg-grey-0` causing no changes when a table row was hovered):

fix visual bug in sidebar team member

---

src/components/molecules/tag-input/index.tsx

**What**
Fix of the tag input `onBlur` behavior.
**Why**
If the user hasn't added a comma as the last input character the last tag would not register.
**How**
Updated the `handleBlur` method to also call the `handleAddValue`.

Fix: Tag input blur case

---

package.json
src/assets/styles/global.css
src/components/molecules/modal/index.tsx
src/components/molecules/select/index.tsx
src/domain/orders/details/claim/create.tsx
src/domain/orders/details/returns/index.tsx
src/domain/orders/details/swap/create.tsx
src/domain/orders/new/components/shipping-details.tsx

**What**
- fix overflow issue with dropdown
**How**
- switch `dropdown` component from `react-multi-select-component` to `react-select` (which has more users, stars and downloads in general)
- `react-select` supports native portalling of the dropdown which enables us to show it as an overlay instead, which `react-multi-select-component` doesn't have
- add `ModalContext` which exposes a ref to the modal portal
this pr replaces #335 because of the pr base and excessive merge conflicts

Fix: dropdown overflow

---

src/components/organisms/body-card.tsx

Closes #352.
Fixes a bug that renders the "fading" gradient effect in the body card in a weird way on Safari.
Apparently, [Safari treats `transparent` differently](https://stackoverflow.com/questions/38391457/linear-gradient-to-transparent-bug-in-latest-safari#:~:text=For%20most%20browsers,along%20the%20gradient.) than other browsers so that gradients that use the `transparent` keyword look weird. 
Also added `rounded-t-rounded` to the overlay so that the corners don't overflow the body card.

fix: broken gradient on safari

---

yarn.lock

Noticed that the jobs we have in our pipeline are failing in a lot of open PRs. This fixes it by updating the registry that should be used for installing `react-select`

fix: change registry used to install react-select

---

src/components/molecules/timeline-events/exchange.tsx

**What**
- use `store.swap_link_template` instead of `store.payment_link_template` to generate the payment link used for the exchange item
**Why**
- the user was unable to copy the payment link and view the chart id

fix: exchange payment link

---

src/components/organisms/currency-input/index.tsx
src/domain/settings/regions/new-shipping.tsx

- fixes currency input styling when `size="full"`
- instead of doing `basis-full` we can just use `flex-1` instead. This allows the currency input to take the full width of the container in case the currency input does not have children, otherwise container width will be split equally between both children

fix: currency input width

---

src/components/templates/discount-general/index.tsx
src/components/templates/discount-table/use-discount-columns.tsx
src/domain/discounts/new/index.tsx

**What**
- Makes it possible to create a `free_shipping` discount.
- Also fixes `location.state` type on `discounts/new`
- also changes "draft" button to "disable"

fix: free shipping discount

---

.storybook/preview.js
src/components/declarative-toaster/declarative-toaster.stories.tsx
src/components/declarative-toaster/index.tsx
src/components/fundamentals/icons/backspace-icon/backspace-icon.stories.tsx
src/components/fundamentals/icons/backspace-icon/index.tsx
src/components/molecules/hot-key-action/hot-key-action.stories.tsx
src/components/molecules/hot-key-action/index.tsx
src/components/molecules/table-toaster/index.tsx

- adds a declarative `Toaster` component
- adds a `HotKeyAction` component
- adds a `TableToasterContainer` component
- `react-hot-toast` provides an imperative API for dealing with toasters. Although this is very useful and nice for a lot of use cases (i.e: onError/onSuccess callbacks), sometimes, it might be better to have a declarative approach. For example, when handling table "batch" actions (i.e: select multiple rows then delete), `react-table` will return a `selectedFlatRows` field which will hold all the rows which are currently selected. We can use this piece of state to determine whether we should render a toaster or not. Instead of making a `useEffect` and subscribing to some piece of state everytime we want to use it this way, I have abstracted this functionality in a …

feat: table actions toaster

---

src/domain/customers/groups/customer-group-modal.tsx
src/domain/customers/groups/details.tsx

**What**
- ~~use `/admin/customers` in combination with the `groups` param to fetch customers for the groups details page instead of using `/admin/customer-groups/:id/customers`~~ 
- remove customer groups filter on the details page
- set metadata filed to `null` if deleted
**Why**
- ~~`/admin/customer-groups/:id/customers` enforces a single `groups` id as a param by design but we have a use case on the CG customers table where we need customers that belong in 2 groups~~

fix: replace the endpoint for fetching customers of a group

---

src/assets/styles/global.css
src/components/organisms/radio-group/index.tsx

- add a border to radio item when selected
- Given that the label element is actually a parent of the radio component, there is no css selector for selecting the parent when the radio is checked. The solution adds an extra `RadioPrimitive.Indicator` which is purely stylistic. It simply renders a violet outline on the parent. The `RadioPrimitive.Indicator` is a component which radix renders when the radio item is checked. You can think about having two instances of this component as a way of saying "when the radio is selected, indicate this by rendering an outline + a little radio icon"
would love to hear if any of you guys can come up with a cleaner and more elegant solution!

fix: radio group styling

---

src/components/molecules/select/index.tsx

- use radio as a start adornment when `Select` is single select
- changed the `Option` component to use different adornments depending on the value of the `isMulti` prop

feat: change styling for single select

---

src/domain/discounts/discount-form/condition-tables/products.tsx
src/domain/discounts/discount-form/condition-tables/selectable-table.tsx

- adds a generic table to be used for different promotion condition modals
- uses same approach as customer-groups + price lists
- supports optional headers
- supports optional filtering
- supports custom rows + headers through the `renderRow` and `renderHeaderGroup` props
- automatically debounces search terms

add: generic table for promotion conditions

---

src/components/molecules/timeline-events/claim/index.tsx

**What**
Fixes 404 on cancel claim
**How**
Provide correct props to `useAdminCancelClaim`

fix: fix 404 on cancel claim

---

src/components/templates/product-table/index.tsx

**What**
- add `is_giftcard=false` to default query params for products

Fix: add `is_giftcard=false` to default query parameters

---

src/domain/products/details/variants/variant-editor.tsx

The 'Add variant' dialog now uses the default store currency when adding a price
Fixes #525 
By passing the store configuration parameters to `usePricesFieldArray`
The change has been manually tested against a fresh Medusa 1.2.1 instance configured with Postgres:
Modified file formatted using ESLint/Prettier with repository provided config

fix: use default store currency when creating variant price

---

src/domain/products/details/variants/variant-editor.tsx
src/domain/products/product-form/sections/variants.tsx

**What**
See #546 for description of errors that are fixed.
**How**
- If no title is provided in the form, create a title from the joining the option values. Same way as we do it when creating a new product w/ variants.
- If not inventory quantity is provided add `inventory_quantity: 0` to the request.
- Add a required `*` to option inputs to signify that they are required to fill out.
- If no prices are entered, focus the `Add price` button, also add required `*` to the Prices label to signify that it is required to add a price.

fix: bugs related to creating variant

---

src/components/molecules/table/index.tsx
src/components/molecules/timeline-events/claim/details.tsx
src/components/organisms/rma-select-product-table/index.tsx

**What**
The `Table` element was incorrectly typed, which resulted in the `colSpan` prop being used wrong in some instances, and TS not detecting these errors.
This fixes the typing of the component and subcomponents, and fixes the wrong uses of `colSpan`.

fix: fixed types of Table component allowing colSpan prop to work as intended

---

src/components/organisms/rma-select-product-table/index.tsx
src/components/organisms/rma-select-receive-product-table/index.tsx
src/domain/orders/details/returns/receive-menu.tsx

**What**
- Fix bug where receiving a partial return would refund the amount of entire quantity of products (i.e. receiving a return of 1/2 items would refund 2/2 items) 
- remove additional line for return reason which added padding when a line was selected in a swap or claim
**Why**
- to ensure that refunds are calculated correctly
**How**
- adjust how the total for the return is calculated
- Add a table specifically for receiving returns where reasons cannot be set (since they are set when registering)

Fix: refund amount on return

---

src/components/molecules/timeline-events/exchange.tsx

**What**
- notification handling when cancelling returns on exchanges and exchanges 
**How**
- make handling methods async and use the delete prompts for cancelling exchanges and returns
**Why**
- previously when cancelling an exchange without first cancelling the return no error was shown and nothing was cancelled

Fix: Notifications when cancelling exchanges

---

src/components/organisms/sidebar-team/index.tsx
src/components/organisms/sidebar/index.tsx
src/context/account.js

**What**
- refresh team sidebar when updating personal information
**Why**
- When updating first name with a different first letter the sidebar did not previously update the avatar to reflect the change
**How**
- refactor sidebar and team sidebar s.t. users query is run in team sidebar query

Fix: Refresh team sidebar when personal information for a user is updated

---

src/components/templates/price-overrides/index.tsx
src/components/templates/price-overrides/price-amount.tsx
src/domain/pricing/details/sections/prices-details/edit-prices-overrides/index.tsx
src/domain/pricing/details/sections/prices-details/edit-prices-overrides/mappers.tsx
src/utils/xorObjFields.ts

- price list overrides modal did not fire a request when the "save and close" button is clicked
- add mutation from `medusa-react`
- fixed behavior of checkboxes when selecting variants

fix: price list overrides does not fire request

---

src/components/templates/add-products-modal/utils.ts
src/domain/pricing/details/sections/prices-details/edit-prices-overrides/index.tsx
src/domain/pricing/details/sections/prices-details/edit-prices-overrides/product-variant-leaf.tsx

- remove console.log
- filtered prices length should be reflected in the product variant tree

fix: prices length in prices overrides modal

---

src/domain/pricing/details/sections/header.tsx
src/domain/pricing/pricing-form/form-header/index.tsx
src/domain/pricing/pricing-form/form/mappers.ts
src/domain/pricing/pricing-form/sections/configuration.tsx

**What**
- toggle "Customer groups" off as default when opening configurations
- ensure that cancel and close on focus modal in pricelist detail closes focus modal
- parse starts_at and ends_at as dates when converting to form values
**Why**
- customer groups was toggled on (because `[]` is truthy) 
- cancel and close navigated to list view from detail when closing modal 
- datepickers were broken when editing due to the form values being strings rather than dates

Fix: Price list focus modal adjustments

---

package.json
yarn.lock

**What**
#577 seems to have stripped the project from React types, resulting in many TS errors. This PR adds the version of `@types/react` that matches the version of React used, as closely as possible.

fix(deps)/re-add @types/react

---

src/domain/pricing/pricing-form/form-header/index.tsx
src/domain/pricing/pricing-form/form/mappers.ts

**What**
- use null updates if `starts_at` or `ends_at` are not configured. 
- use empty array updates if `customer_groups` are not defined
**Why**
- to allow removing configurations in price lists

Fix: Allow null updates for starts_at ends_at and customer groups

---

src/components/templates/product-table/index.tsx

**What**
- include status in product table query
**Why**
- To allow switching between "publish" and "unpublish" in the actionables for a row
- To include a descriptive status dot in the status column
**Testing**
Before
After

include status in product query for table

---

src/domain/orders/draft-orders/details.tsx

**What**
- fixed Link to Order from DraftOrder broken
**How**
- Removed the extra `}` in the end of the the link
Closes https://github.com/medusajs/admin/issues/564

fix: Link to Order from DraftOrder broken

---

src/components/templates/selectable-table/index.tsx

- fixes the spinner's position in the `SelectableTable` component
- micro improvement to the UX/UI
- gave the table a min-height, then wrapped the spinner inside a div and centered it
Closes #584

fix: center spinner in selectable table

---

src/components/organisms/rma-select-product-table/index.tsx

**What**
Creates a simple way for store operators to copy SKUs when creating claims and exchanges.

feat: add quick way to copy skus when creating swaps/claims

---

src/domain/gift-cards/manage/form/mappers.ts
src/domain/products/product-form/form/mappers.ts

What
When the last image is removed from a product or gift card, the thumbnail persists. This gives the illusion of the image not being properly deleted. To avoid confusion, this PR removes the thumbnail if all images are removed from a product or gift card.
Note
fixes #626

fix: remove thumbnail when removing all images

---

src/domain/orders/details/index.tsx
src/domain/orders/details/order-line/index.tsx

**What**
Admin throws when retrieving order with deleted region because it's trying to access currency code of null

fix: Use order currency code instead of region on order lines

---

src/assets/styles/global.css
src/components/fundamentals/badge/index.tsx
src/components/fundamentals/icons/channels-icon.tsx
src/domain/products/product-form/index.tsx
src/domain/products/product-form/sections/sales-channels.tsx

**What**
- Add sales channels element to product form guarded by a featureflag
**How**
- Add an additional badge variant
- Limit to show 3 (+ N more) sales channels
Fixes CORE-269

Feat: Product detail sc info

---

package.json
src/assets/styles/emoji-picker.css
src/components/atoms/input-error/index.tsx
src/components/atoms/tooltip/index.tsx
src/components/fundamentals/icons/icons-overview.stories.tsx
src/components/fundamentals/input-header.tsx
src/components/molecules/emoji-picker/index.tsx
src/components/molecules/input/index.tsx
src/components/molecules/modal/index.tsx
src/components/molecules/select/index.tsx
src/components/molecules/tag-input/index.tsx
src/components/molecules/textarea/index.tsx
src/components/molecules/textarea/textarea.stories.tsx
src/components/organisms/help-dialog/index.tsx
src/components/organisms/topbar/index.tsx
src/domain/discounts/details/general/edit-general.tsx
src/domain/discounts/new/discount-form/sections/general.tsx
src/domain/gift-cards/custom-giftcard.tsx
src/domain/gift-cards/new.tsx
src/domain/pricing/pricing-form/sections/product-prices.tsx
src/domain/products/product-form/form/product-form-context.tsx
src/domain/products/product-form/sections/general.tsx
src/domain/settings/taxes/edit-form.tsx
yarn.lock

**What**
- Updates the look of `<InputField />`, and also improves the typing of the component.
- Updates the look of `<TextArea />`.
- Updates the look of `<TagInput />`
- Temporary update to look of `<Select />`, only so that the height matches the other inputs. We will need to do a bigger revamp of the Select component in a separate PR.
**>> Again note that the look of select is temporary, as it requires a bit of a rework to align with the new design <<**

feat: revamp input fields

---

src/domain/pricing/details/sections/prices-details/edit-prices-overrides/index.tsx

**What**
We want to display a Toaster when editing prices for a Product in a PriceList
Steps to reproduce:
1. Create PriceList
2. Edit Prices on a single product
3. Save and submit
**How**
Used `useNotification` hook when a mutation is successful. The resulting function from the `useNotification` hooks is invoked as such: `notification("Success", "Price overrides updated", "success").`
Closes #586

feat: Show Toaster when editing Product in PriceList

---

src/domain/pricing/pricing-form/form-header/index.tsx
src/domain/pricing/pricing-form/form/mappers.ts
src/domain/pricing/pricing-form/form/pricing-form-context.tsx
src/domain/pricing/pricing-form/sections/general.tsx
src/domain/pricing/pricing-form/types/index.ts

**What**
- include switch for setting/updating `includes_tax`
**How**
- expand update and create methods in the pricelist form header to set `includes_tax` if feature is enabled, otherwise it wont be set 
Fixes CORE-402

Feat(admin): Toggle tax inclusivity for price lists

---

src/components/organisms/currency-input/index.tsx
src/components/organisms/medusa-price-input/index.tsx
src/components/organisms/price-input/index.tsx
src/domain/products/components/prices-form/price-form-input.tsx

**What**
- Fixes a bug where cents/fractions were ignored when using the admin dashboard in a browser with a locale that uses commas as the decimal separator.
**How**
- Instead of using `parseFloat` to get the value that should be used to calculate the persisted amount, we instead use the float that is returned as part of the `onChange` function in react-currency-input-field.
Closes #630 
Closes CORE-595

fix: amount inputs work with locales that use comma separators

---

src/components/molecules/select/next-select/use-select-props.tsx

**What**
- Prevent having duplicate select options in `isMulti` NextSelects
**How**
- use deep equality check to filter unselected options.
Closes #700

hotfix: avoid duplicate select options

---

src/utils/payment-providers-mapper.ts

This PR adds missing labels for payment providers.

Add labels for stripe-blik and stripe-przelewy24 payments

---

src/components/atoms/two-step-delete/index.tsx
src/components/atoms/two-step-delete/two-step-delete.stories.tsx

**What**
- Allows passing className and children to the `TwoStepDelete` button.
**How**
- Add `className` as optional prop
- Add optional `children` as optional prop, if no children are passed we render a `TrashIcon` as was done in the initial design.
Closes CORE-487

feat: allow custom children and styling of TwoStepDelete

---

src/domain/settings/regions/region-overview/index.tsx

**What**
- Adds check that prevents error if navigating to `settings/regions` when there are no regions in the store.

hotfix: prevent error on no regions in store

---

src/domain/products/components/general-form/index.tsx

**What**
- Removes validation of product description input, as it was preventing users from creating multi-line descriptions. 
Closes #710

hothix: remove validation from description

---

src/components/templates/product-table/index.tsx
src/domain/products/edit/sections/variants/index.tsx

**What**
- Fixes an issue where option pills on the product edit page would overflow.
- Also fixes an issue where query props in ProductTable were wrong, resulting in the collection_id of the products not being returned from the API request.
Closes CORE-652

fix: option pill overflow

---

src/components/molecules/rma-select-shipping/index.tsx
src/domain/orders/details/claim/create.tsx
src/domain/orders/details/swap/create.tsx

**What**
- Fixes bug that was preventing custom shipping prices from being sent as part of a swap create payload if the price was 0.
- Also if the value of the custom shipping price field is set to `undefined`, but the price is not deleted using the `delete` button, it will be interpreted as meaning that the cost of return shipping should be 0.
Closes CORE-569

fix: allow custom shipping price of 0 in swap

---

src/components/private-route/index.js
src/pages/a.js

**What**
- prevent showing the layout in a flash before the login screen when navigating unauthenticated to a page under `/a/*`
**How**
- wrap the components in `pages/a` in a `privateRoute` 
Fixes CORE-439

Fix(medusa): prevent showing protected routes when loading unauthenticated admin

---

src/domain/products/edit/sections/general/index.tsx

The paragraph on product description doesn't preserve new lines.
This PR adds `white-space: pre-wrap` css to preserve new lines
Before:
After:

Add white-space:pre-wrap to product description

---

src/domain/products/components/prices-form/index.tsx
src/domain/products/edit/sections/variants/add-variant-modal.tsx

**What**
- The `createAddPayload` was defaulting unset prices to 0. This was an issue since we now load every possible price that the user can set for a variant. The expected behaviour would be that if the user does not set one of these prices to anything then they won't be added to the `variant.prices` array, but this was not the case. This fix ensures that all prices where the amount is not specifically set (meaning that they are null or undefined) won't be passed on to the server.

hotfix: fix unset prices on variant creation

---

src/components/molecules/timeline-events/exchange.tsx
src/components/molecules/timeline-events/order-edit/canceled.tsx
src/components/molecules/timeline-events/order-edit/confirmed-difference-due.tsx
src/components/molecules/timeline-events/order-edit/created.tsx
src/components/molecules/timeline-events/order-edit/index.tsx
src/components/molecules/timeline-events/order-edit/refund-difference-due.tsx
src/components/molecules/timeline-events/order-edit/requested-difference-due.tsx
src/components/molecules/timeline-events/order-edit/requested.tsx
src/components/organisms/timeline/index.tsx
src/domain/orders/details/index.tsx
src/domain/orders/details/order-line/edit.tsx
src/domain/orders/details/refund/index.tsx
src/domain/orders/edit/context.tsx
src/domain/orders/edit/modal.tsx
src/domain/orders/edit/variants-table.tsx
src/hooks/use-build-timeline.tsx

**What**
- fix bugs, align implementations of the modal and the timeline, fetch optimisations
**TODO**

fix: OE UI polish

---

src/components/molecules/modal/stepped-modal.tsx
src/domain/orders/new/new-order.tsx

Prevent resetting stepped modal before submission is finished:
https://user-images.githubusercontent.com/88927411/199168969-50284840-78f9-46bc-835d-361a27c15d28.mov

feat(admin): move draft order reset to success method

---

src/domain/settings/regions/components/shipping-option-card/edit-modal.tsx
src/domain/settings/regions/components/shipping-option-form/index.tsx
src/domain/settings/regions/edit/shipping-options/create-shipping-option-modal.tsx
src/types/shared.ts

Here are the changes that were made to the layout during the fix:
- price type dropdown was added

fix: option to select price_type (#597)

---

.changeset/new-maps-breathe.md
src/domain/orders/details/index.tsx

**What**
- Show the correct date in order detail
**How**
- update the formatting string to display day of month, previously it displayed day of week by number
**Testing**
- open an order with a date placed > 7 and verify that it has the correct date
https://momentjscom.readthedocs.io/en/latest/moment/04-displaying/01-format/
Fixes CORE-694

Fix: use day of month rather than day of week

---

src/domain/orders/details/order-line/index.tsx
src/domain/orders/draft-orders/details.tsx

The server return now the totals on each item of and order and cart. Use this value to display the correct amount in the order and draft order details and do not rely on the taxes locally.
depends on https://github.com/medusajs/medusa/pull/2546
FIXES CORE-687

fix: draft order and order display the item price incorrectly when includes taxes

---

src/hooks/use-build-timeline.tsx

**What**
- Fixes invalid hook use inside of a `useMemo`.
- Cleans up dependency array of memorized events.

fix: Invalid hook use and cleans up dependency array

---

src/components/molecules/modal/focus-modal.tsx
src/domain/discounts/new/discount-form/index.tsx
src/domain/discounts/new/index.tsx

Seems like a `"@reach/router"` import snug in or was missed when resolving merge from #800 to #802.
I've kept the usage of `location.state?`, though based on a quick code search, I don't see this being set or used anywhere else. May be stale code and safe to remove?

Remove sneaky @reach/router usage

---

src/domain/orders/edit/modal.tsx
src/main.tsx

**What**
- the issue manifested in the order timeline which displayed (multiple) "created" order edit events
**Why**
- when we open the OE modal, a POST request is dispatched that will create a new OE on the order - this is done in an `useEffect` hook on mount
- if the newly upgraded React 18 is run in [strict mode](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-strict-mode), mount effects will be called twice (i.e. each component will be mounted, unmounted and mounted again)
- this will cause the creation of two order edits, and while the second one is being deleted when the modal is closed, first one still exists
**How**
- the fix is to only dispatch POST request on the first mount
---
FIXES CORE-840

fix: remount of OE modal

---

yarn.lock

**What**
- The medusa-cli dependency was locked to a local version in the latest release. This PR fixes the issue, so the dependency is pulled from npm instead.

fix: remove local dependency

---

netlify.toml

Fixed deploy directory of the Netlify button to publish the `public` directory following the change to vite.

chore: fix deploy directory for Netlify button

---

src/components/molecules/timeline-events/order-edit/confirmed.tsx
src/components/molecules/timeline-events/order-edit/declined.tsx
src/domain/orders/edit/utils/user.ts

**What**
- fix the "Order declined" timeline event declined reason display
- properly fetch user/customer that declined the edit
---
FIXES CORE-883

fix: OE "declined" timeline event

---

src/domain/products/edit/sections/general/index.tsx

Fixes [Issue#850](https://github.com/medusajs/admin/issues/850), many product tags overflowing the container. Screenshot in issue for bug.
Adds a wrapping rule to the container and some vertical padding between tags.
Resolves CORE-947.
Reopened with correct base.

fix: Product tags overflowing in product view

---

src/components/atoms/avatar/index.tsx
src/components/fundamentals/icons/cart-icon/cart-icon.stories.tsx
src/components/fundamentals/icons/cart-icon/index.tsx
src/components/molecules/notification-bell/index.tsx
src/components/molecules/sidebar-menu-item/index.tsx
src/components/molecules/user-menu/index.tsx
src/components/organisms/sidebar/index.tsx
src/components/organisms/topbar/index.tsx

**What/How/Why?**
Very first stage of sidebar redesign.
- Moved the avatar/user menu from the top bar to the sidebar (and to its own component in the process)
- Changed the store name display 
- Slight redesign of the menu items, dropped the purple from active items, changed the greys a little, made the active item background borders more rounded
- Re-ordered Products/Customers/Orders, updated some of the icons
- Renamed Discounts to Promotions
As a sidenote, for most of my PRs updating files that contain tailwind classes: my linter re-orders the classes in what Tailwind considers the "correct" order. Makes some PRs a little more annoying to review, but have spoken to Oli and we'd like to move towards enforcing this linting rule repo-wide soon.
Closes CORE-951.

feat: Initial sidebar redesign

---

src/domain/products/edit/sections/variants/add-variant-modal.tsx
src/domain/products/edit/sections/variants/edit-variant-modal.tsx
src/domain/products/edit/sections/variants/table.tsx

**What**
- Fixes an issue where duplicating a variant would result in an error due to a price with the provided ID already existing.

fix: duplicate variant fails due to `price.id` constraint

---

src/domain/pricing/pricing-form/sections/prices.tsx

**What**
- Use `isInitialLoading` instead of `isLoading` if `isEdit` is `false`
Resolves CORE-1054

hotfix: loading price list prices in a non-edit context

---

src/domain/products/new/add-sales-channels.tsx
src/domain/products/new/index.tsx

**What**
- Remove duplicated default sales channel entries in product sales channel array
- Use a flag to determine if users have removed the default sales channel from the product payload to prevent it from being re-added unless the user adds it themselves
Resolves CORE-1069

hotfix: Dedup default sales channel on product creation

---

src/domain/orders/details/rma-sub-modals/products.tsx
src/domain/orders/new/components/items.tsx
src/domain/orders/new/components/select-region.tsx
src/domain/orders/new/form/index.tsx
src/utils/prices.ts

**What**
- Fix nested modal error with products page that would cause claim to fail
- Support for changing regions in draft orders
**How**
- Move price calculations for new variants to the draft order flow rather than the sub-modal products screen
- Update field array when updating quantities
- Update prices when changing regions in the new-order form
Fixes CORE-1082

fix: Create DraftOrder flow

---

src/domain/orders/edit/context.tsx
src/domain/orders/edit/modal.tsx

**What**
- I've noticed that this started to occur after we updated `react-query` recently so I presume that async flow is different now causing `activeOrderEditId` to be set to `undefined` before the last effect call in the modal is triggered. Fixed by explicitly removing active edit id after the modal is hidden.
---
FIXES CORE-1047

fix: running effect after OE modal closes

---

src/domain/discounts/new/discount-form/sections/general.tsx

**What**
- logic for rendering the form with regions dropdown was relying on `setTimeout` of 100ms but in a case where a response with regions would take longer than that, an empty dropdown would be rendered
---
FIXES CORE-1099

fix(discounts): race condition causing empty regions list to be rendered sometimes
