medusajs/admin

src/domain/orders/new/components/shipping-details.js
=> Bug: searching for customers via email crashes react-select #80

package.json, src/components/availability-duration/index.js, src/components/date-picker/date-picker.js, src/components/info-tooltip/index.js, src/components/multi-select/index.js, src/components/tooltip/index.js, src/domain/discounts/details/discount-rule/index.js, src/domain/discounts/details/index.js, src/domain/discounts/new/index.js, src/domain/gift-cards/manage/index.js, src/domain/settings/regions/new.js, src/services/request.js, src/theme/breakpoints.js
This PR is dependant on [Feat:discount expiration date](https://github.com/medusajs/medusa/pull/403) in medusa core
**What?**
- Add ui for selecting starts_at and ends_at dates during discount creation and editing
- Add ui for picking a duration in discount creation and editing if the discount is dynamic
**Why?**
- To allow admins to create limited time discounts and offers
**How?**
- Adding a new component for picking a duration
- Conditionally including timestamps in the react-datepicker component
**Testing**
Manual testing
=> Feat:discount code expiration

src/domain/products/details/images/index.js
- Do not include the thumbnail image in the list of images so the user does not confuse these as the same.
=> Fix: removed thumbnail from display of images

src/domain/gift-cards/manage/detail.js
=> fix: Update return URL while deleting gift cards

src/assets/styles/global.css, src/components/fundamentals/button/index.tsx
**What** 
- fix styling issue with tailwind
=> Fix: button styling

package.json, src/components/atoms/avatar.tsx, src/components/molecules/sidebar-team-member/index.tsx, src/components/organisms/sidebar-team/index.tsx, src/components/organisms/topbar.tsx, yarn.lock
**What** 
- Implement the avatar atom using radix avatar component
**How**
- adapt existing styling to the radix avatar component
- make avatar scale to 100% width and height to fit whatever contain it's put in
**Why**
- To avoid having multiple avatar components
- to utilise the fallback function of radix avatar
=> Feat: Revamp avatar

src/domain/settings/regions/details.tsx
**What**
- fix display issue in region details (line 127 - 128)
- formatting after installing typescript linting
=> Fix: use value object for dropdown

src/components/fundamentals/badge/index.tsx
=> remove unused code

src/components/atoms/file-upload-field/file-upload-field.stories.tsx, src/components/atoms/file-upload-field/index.tsx, src/components/organisms/file-upload-modal/index.tsx
**What**
- refactor file upload from personal information to separate component
- add file upload storybook
=> Feat: Revamp file upload atom

src/components/molecules/modal/index.tsx, src/components/organisms/delete-prompt.tsx, src/domain/settings/regions/edit-shipping.tsx
**What**
- delete prompt for deletion of shipping option
=> Fix:delete prompt for shipping option

.github/workflows/chromatic.yml, package.json, yarn.lock
- adds automatic deployments to Chromatic on every PR
- enhance review process
=> add: chromatic github actions for storybook deploys on every PR

src/components/fundamentals/icons/chevron-up.tsx, src/components/fundamentals/icons/clipboard-copy-icon/index.tsx, src/components/molecules/view-raw/index.tsx, src/components/molecules/view-raw/view-raw.stories.tsx, tailwind.config.js
**What**
- Adds component to view raw json data
- extends ReactJSON with the new design
=> feat: raw data component

src/components/organisms/currency-input/index.tsx, src/domain/gift-cards/custom-giftcard.tsx, src/domain/gift-cards/overview.tsx, yarn.lock
**What** 
- custom discount modal
- Include updates to currentCurrency of currencyInput
=> Feat: Revamp custom gift card

src/domain/settings/regions/details.tsx, yarn.lock
**What**
Fixes currency code not being part of update to region
=> fix: currency code not part of update to region

src/pages/login.tsx
**What**
- feedback when login credentials are invalid
=> add login feedback

src/domain/settings/index.js
**What changes are in the PR?**
Fixed the typo in currencies subtitle
**Why these changes are relevant?**
To have a good UI/UX
**How have the changes been implemented?**
Changed `wil` to `will`
**How has the changes been tested or how can the reviewer test the feature?**
Login to the admin ->  Go to the settings page and verify changes
=> Fixed: typo in currencies subtitle(#298)

src/domain/settings/details.tsx, src/domain/settings/index.js, src/domain/settings/personal-information.tsx
**What changes are in the PR?**
Fixed the typo in settings cards components and the breadcrumbs
**Why these changes are relevant?**
To have a good UI/UX
**How have the changes been implemented?**
Changes the casing of titles to upper camel case
**How has the changes been tested or how can the reviewer test the feature?**
Login to the admin ->  Go to the settings page and verify changes
=> Fixed: the casing in the settings card titles(#298)

src/components/templates/gift-card-table/index.tsx, src/domain/gift-cards/details/edit-gift-card-modal.tsx, src/domain/gift-cards/details/index.tsx, src/domain/gift-cards/details/update-balance-modal.tsx, src/domain/gift-cards/index.tsx
Adds gift card details page
Includes:
- Edit gift card region
- Update gift card balance
=> feat: Gift Card details page

gatsby-browser.js, src/components/molecules/modal/layered-modal.tsx, src/components/molecules/modal/stepped-modal.tsx
=> Feat: Stepped modal

src/components/molecules/note-input/index.tsx
**What**
- Prevents NoteInput send button from refreshing entire page onSubmit
- Also fixes incorrectly named NoteInputProps
=> fix: NoteInput on Timeline no longer refreshes page

src/components/atoms/settings-card/index.tsx
**What changes are in the PR?**
Added h-full class to the setting card button
**Why these changes are relevant?**
To have good and consistent UI
**How have the changes been implemented?**
Added height 100%
**How has the changes been tested or how can the reviewer test the feature?**
Tested the changes on frontend, and you can verify it by redirecting to the settings page
Before:
After:
=> Fix: the UI issue on the settings page card

src/assets/styles/global.css, src/components/atoms/number-scroller/index.tsx, src/components/molecules/filter-dropdown/container.tsx, src/components/molecules/modal/index.tsx, src/components/organisms/body-card.tsx, src/components/organisms/sidebar/index.tsx, src/components/templates/collection-product-table/add-product-table.tsx, src/components/templates/collection-product-table/index.tsx, src/components/templates/collection-product-table/view-products-table.tsx, src/components/templates/collections-table/index.tsx, src/components/templates/customer-orders-table/index.tsx, src/components/templates/customer-table/index.tsx, src/components/templates/discount-table/index.tsx, src/components/templates/draft-order-table/index.tsx, src/components/templates/gift-card-table/index.tsx, src/components/templates/order-table/index.tsx, src/components/templates/product-table/index.tsx, src/components/templates/user-table.tsx, src/domain/customers/details/index.tsx, src/domain/gift-cards/manage/denomination-table.tsx
- adds a new scrollbar design
- changes occurences of `overflow-y-scroll` to overflow-y-auto` to only bring up the scrollbar when needed
=> fix: scrollbar styling

src/domain/orders/details/claim/create.tsx
**What**
- remove commented out code
- use correct variable name for currency code in rma shipping price component
=> Fix: Shipping method price in create claim

src/domain/products/new.tsx
**What** 
- only upload images if any images are present, otherwise dont send the request to the server 
fixes #350
=> Fix: file upload error with no files uploaded

src/domain/products/new.tsx, src/domain/products/product-form/form/mappers.ts, src/domain/products/product-form/index.tsx, src/domain/products/product-form/sections/general.tsx
- support publishing/unpublishing products through the edit products page
- support setting whether a product should be discountable or non-discountable
=> fix: missing product details

src/components/variant-grid/index.tsx, src/domain/products/details/variants/variant-editor.tsx, src/domain/products/product-form/form/product-form-context.tsx, src/domain/products/product-form/sections/variants.tsx, src/domain/products/product-form/utils/index.ts
- Add support for adding variants
- Tweaked the existing `VariantEditor` component to support both adding and editing variants
=> fix: add variant modal

src/components/molecules/timeline-events/exchange.tsx, src/domain/orders/details/rma-sub-modals/products.tsx
**What**
- Fixes receive return on swaps
- Adds actionable to capture payments on swaps
=> fix: : swap receive and payment

src/components/organisms/raw-json/index.tsx, src/domain/customers/details/index.tsx, src/domain/discounts/details/index.tsx, src/domain/gift-cards/details/index.tsx, src/domain/orders/details/index.tsx, src/domain/products/product-form/index.tsx
**What**
- add `RawJSON` component which renders JSON tree section
- added "Raw _\<entity\>"_ sections to the Product/Gift/Customer/Discount details pages
=> feat: add `RawJSON` component

src/components/molecules/filter-dropdown/save-field.tsx, src/components/molecules/select/index.tsx, src/components/molecules/table/index.tsx, src/components/organisms/currency-input/index.tsx, src/components/templates/product-table/use-product-filters.ts, src/components/variant-grid/index.tsx, src/domain/products/details/variants/variant-editor.tsx, src/domain/products/product-form/form/mappers.ts, src/domain/products/product-form/form/product-form-context.tsx, src/domain/products/product-form/form/usePricesFieldArray.ts, src/domain/products/product-form/sections/general.tsx, src/domain/products/product-form/sections/prices.tsx, src/domain/products/product-form/sections/stock-inventory.tsx, src/utils/trim-values.ts
- fixes bugs reported in the product bug hunt
Depends on:
- #399 
- #404
=> fix: product bug hunt fix

src/components/templates/collections-table/index.tsx
**What**
- Pagination was not updating offset on query in CollectionsTable.
=> fix: pagination on collection table

src/domain/orders/draft-orders/details.tsx
=> fix: show draft order

src/components/molecules/select/index.tsx, src/domain/products/product-form/sections/general.tsx
**What**
- Makes it possible to create new product types in the "Type" dropdown on products page.
- Always enables search on createable selects
=> fix: make type createable

src/domain/orders/details/utils/create-filtering.js
**What**
- Resolves #426
- Dependant on [#1182](https://github.com/medusajs/medusa/pull/1182)
=> fix: claim additional_items & update create filtering

package.json, src/components/atoms/tooltip/index.tsx, src/components/organisms/accordion/accordion.stories.tsx, src/components/organisms/accordion/index.tsx, tailwind.config.js, yarn.lock
**What**
- adds new accordion component.
=> feat: accordion component

package.json, src/components/atoms/switch/index.tsx, src/components/atoms/switch/switch.stories.tsx, tailwind.config.js, yarn.lock
**What**
- add new `Switch`component using Radix primitives
=> feat: `Switch` atom

src/components/atoms/fade-wrapper/fade-wrapper.stories.tsx, src/components/atoms/fade-wrapper/index.tsx, src/components/molecules/modal/focus-modal.stories.tsx, src/components/molecules/modal/focus-modal.tsx
**What**
- Add focus modal
**How** 
-  Add absolute element on top of everything with modal-like properties
**Testing**
- Add storybook stories `Molecules/Focus-modal`: 
- `regular`
- `overflow`
=> Feat: Add focus modal

src/components/molecules/modal/focus-modal.tsx
**What**
- Removes width constrains on focus modal main
=> fix: FocusModal Main width

src/components/fundamentals/icons/download-icon.tsx, src/components/fundamentals/icons/file-icon.tsx, src/components/fundamentals/icons/warning-circle.tsx, src/components/organisms/upload-modal/index.tsx, src/components/organisms/upload-modal/upload-modal.stories.tsx
**What**
- added "upload prices" modal  
**Note**
- still a few TODOs (& logs) left which will be resolved when the actual integration of the component is done
- the modal component should be moved somewhere in the domain folder?
=> feat: upload prices modal

src/domain/discounts/discount-form/condition-tables/customer-groups.tsx, src/domain/discounts/discount-form/condition-tables/products.tsx, src/domain/discounts/discount-form/condition-tables/selectable-table.tsx, src/domain/discounts/discount-form/form/discount-form-context.tsx, src/domain/discounts/discount-form/use-condition-modal-items.tsx
- adds screen for adding promotion conditions on customer groups
Depends on: #498
=> feat: promotion conditions customer groups

src/assets/styles/global.css, src/components/organisms/price-input/index.tsx, src/components/organisms/price-input/price-input.stories.tsx
**What**
- add an organism input component for editing price list item price
=> feat: price input

src/domain/orders/details/returns/index.tsx
**What**
- fix bug described in #521
=> Fix: Pass correct parameter name to subcomponent

src/components/atoms/copy-to-clipboard/index.tsx, src/domain/orders/details/index.tsx
**What**
Adds Gift Card to order summary
Closes #478
=> fix: show gift card on order summary

src/domain/orders/draft-orders/details.tsx
**What**
- add payment link to draft orders overview according to the design
=> add payment link to draft order detail

src/components/atoms/date-picker/date-picker.tsx, src/components/atoms/date-picker/time-picker.tsx, src/components/fundamentals/input-container.tsx, src/components/molecules/table/table-search.tsx
**What**
- align border radius for inputs in admin
**How**
- change `rounded` or `rounded-base` to `rounded-rounded` in relevant components
*note*: let me know if i missed any inputs
=> Feat: Align border radii

src/domain/pricing/details/sections/prices-details/index.tsx, src/domain/pricing/pricing-form/index.tsx, src/domain/pricing/pricing-form/sections/product-prices.tsx
- remove UI for file upload in the prices section 
- remove "import price list" section
- no medusa core support yet
=> fix: kill import section in prices section

src/components/organisms/product-variant-tree/index.tsx, src/components/templates/price-overrides/index.tsx, src/domain/pricing/details/sections/prices-details/edit-prices-overrides/index.tsx, src/domain/pricing/details/sections/prices-details/edit-prices-overrides/mappers.tsx, src/domain/pricing/details/utils.ts, src/domain/pricing/pricing-form/form-header/index.tsx, src/domain/pricing/pricing-form/form/mappers.ts, src/domain/pricing/pricing-form/form/pricing-form-context.tsx, src/domain/pricing/pricing-form/sections/prices.tsx, src/domain/pricing/pricing-form/sections/product-prices.tsx, src/domain/pricing/pricing-form/types/index.ts
- remove hard coded variant value from form mapper
- use price overrides modal to edit prices when creating a price list
=> fix: create price list form

src/components/organisms/product-variant-tree/index.tsx, src/domain/pricing/details/index.tsx, src/domain/pricing/details/sections/header.tsx, src/domain/pricing/details/sections/prices-details/edit-prices.tsx, src/domain/pricing/pricing-form/form-header/index.tsx, src/domain/pricing/pricing-form/form/mappers.ts
- fixes the "edit manually" feature
- The `<ProductPrices />` component was using the form hook without being wrapped inside a `PriceListFormProvider`. 
- Moved logic around so that the `EditPrices` component also works as expected (while waiting for the bulk editor to come in)
=> fix: price list details edit manually

src/pages/a.js
**What**
- Add `Collections` route, since it seems to have disappeared in the latest version of develop.
=> fix: re add collection route

src/domain/pricing/details/sections/prices-details/prices-table/index.tsx
- add ability to remove product prices from a price list
- add action to remove prices from the prices table in the price list details view
Closes #585
=> add: remove product prices from price list

src/components/organisms/rma-select-receive-product-table/index.tsx, src/domain/orders/details/order-line/index.tsx, src/domain/orders/details/returns/index.tsx, src/domain/orders/details/returns/receive-menu.tsx, src/utils/prices.ts
Fixes an issue where tax prices are displayed improperly.
=> fix: tax related prices

README.md, netlify.toml
- Added `netlify.toml` file to allow "Deploy to Netlify" button to work which will be added in the documentation.
- Added the button in the README
=> Added Deploy to Netlify button

src/components/molecules/form-toaster/index.tsx
**What**
- fix an issue where products couldn't be created with initial variants
**How**
- by fixing wrong memoization - the function that provided variant data upon submission had stale closure
fixes https://github.com/medusajs/admin/issues/625
=> fix: product creation with variants

src/components/templates/customer-orders-table/index.tsx, src/domain/customers/details/index.tsx
**What**
- fix gradient element positioning on the customer details page
- fix fetching orders details for a customer
FIXES CORE-324
=> fix: gradient element positioning

src/components/templates/order-table/index.tsx, src/components/templates/order-table/use-order-column.tsx, src/components/templates/product-table/index.tsx, src/components/templates/product-table/use-product-column.tsx, src/domain/orders/details/index.tsx, src/utils/sales-channel-compare-operator.ts
**What**
- Include sales channels in product table
- Include sales channels in order table
- Display sales channel in order detail 
Fixes CORE-290
Fixed CORE-298
=> Feat: Extend product and order UI with saleschannels

src/components/templates/customer-group-table/customers-list-table.tsx
=> Fixed: the title for pagination on customer groups page

src/context/feature-flag.tsx
**What**
- Add validation for the existence of feature flags in feature flag context
**Why**
- validation failing without an updated core project when cloning admin fresh
=> Fix: feature flag context when ff doesnt exist

src/domain/collections/details/index.tsx
**What**
- include overrides of metadata with null
=> Fix: Remove metadata on collections

src/components/templates/user-table.tsx, src/domain/settings/details.tsx, src/pages/invite.tsx
**What**
- Add "copy invite link" to actionables for invites in the user table
- Update format of invite link template in store settings
**How**
- lift admin url from store, if it's not present on the store use the current window url as a base for generating the invite link using `window.location.origin`
Fixes CORE-453
=> Feat(admin): Add copy invite link in teams page

package.json, src/components/atoms/includes-tax-tooltip/index.tsx, src/components/molecules/select/next-select/components/containers.tsx, src/components/molecules/select/next-select/use-select-props.tsx, src/domain/settings/regions/components/region-form/region-details-form.tsx, src/domain/settings/regions/components/shipping-option-form/index.tsx, src/domain/settings/regions/edit/general-section/edit-region.modal.tsx, yarn.lock
**What**
- Adds toggle to decide if region has TIP.
- Added new TIP Tooltip.
- Show whether region has TIP when adding shipping prices and requirements.
>> Note might need to move the TIP toggle to tax settings depending on this discussion: https://www.figma.com/file/PluqU9Ind9yvD9JbGCkI35?node-id=3231:11131#265755434 <<
=> feat: tax inclusive pricing in region settings

src/components/organisms/batch-jobs-activity-list/index.tsx, src/domain/products/batch-job/import.tsx
**What**
- extend batch job descriptions to support other states
- reset batch job id when import file is removed
=> fix: batch job descriptions

src/domain/settings/regions/components/region-form/region-details-form.tsx, src/domain/settings/regions/new/index.tsx, src/domain/settings/taxes/edit-form.tsx, src/domain/settings/taxes/edit-tax-rate-details.tsx, src/domain/settings/taxes/new.tsx, src/domain/settings/taxes/tax-rule-selector.tsx
**What**
- Ensure a uniform experience when adding tax rates in both region and tax settings.
Closes CORE-559
=> fix: realign tax rate inputs across region and tax settings

src/domain/discounts/new/discount-form/form/discount-form-context.tsx, src/domain/discounts/new/discount-form/form/mappers.ts, src/domain/discounts/new/discount-form/index.tsx, src/domain/discounts/new/discount-form/sections/discount-allocation.tsx, src/domain/discounts/new/discount-form/sections/discount-type.tsx
**What**
- Allow admins to choose allocation type for fixed discounts, all other types default to total allocation.
Closes CORE-430
=> fix: Add allocation setting to create discount form

src/domain/products/components/prices-form/nested-price.tsx
=> hotfix: Pass includes tax to variant price

src/components/organisms/topbar/index.tsx
Related to issue: https://github.com/medusajs/admin/issues/705
=> fix: Hide notification bell on no activity

src/domain/settings/regions/edit/shipping-options/create-shipping-option-modal.tsx
Misleading title in modal when adding shipping option.
=> hotfix: Title in shopping options modal

src/domain/settings/regions/region-overview/region-card.tsx
=> fix: Use fulfillment providers in region item card

src/components/organisms/activity-drawer/index.tsx, src/components/organisms/batch-jobs-activity-list/index.tsx, src/components/organisms/topbar/index.tsx, src/components/templates/layout.tsx, src/context/polling.tsx, src/domain/orders/index.tsx, src/domain/pricing/batch-job/import.tsx, src/domain/products/batch-job/import.tsx, src/domain/products/overview/index.tsx
**What**
- refactor batch job polling to minimise the number of requests
**How**
- refactor the polling context to use dynamic increasing intervals for refresh
- retrieve a batch job by using a hook which refreshes automatically depending on the status of the batch job
---
**RESOLVES CORE-648**
=> refactor: BatchJob polling 

src/domain/products/batch-job/import.tsx
**What**
- use the protected file upload from https://github.com/medusajs/medusa/pull/2433 when creating imports
=> fix: use upload protected file instead of upload file for imports

src/components/organisms/confirmation-prompt.tsx, src/domain/orders/draft-orders/details.tsx
**What**
- display a confirmation prompt when marking a draft order as paid
---
RESOLVES CORE-580
=> feat: draft order confirmation

src/domain/settings/index.js
Please fix this. Triggers my OCD.
=> Fix spelling mistake

src/components/molecules/timeline-events/order-edit/created.tsx, src/domain/orders/edit/modal.tsx
**What**
- fix timeline displaying memoised OE state
- change how the totals are displayed in the order edit modal
---
FIXES CORE-761
FIXES CORE-762
=> fix: OE totals and timeline memoization

src/domain/customers/groups/customer-group-modal.tsx
**What**
Fix CustomerGroup update operation. Match submitted payload to API request body shape.
**Test**
* Go to an existing customer group's page.
* Click on three dots at the right of its name and choose edit.
* Make any changes.
* Click on the Edit Group button.
* Expect Successful operation.
Fixes CORE-682
=> fix: CustomerGroup update operation

src/components/organisms/analytics-config-form/index.tsx, src/components/organisms/analytics-preferences/index.tsx, src/components/organisms/error-boundary/index.tsx, src/context/analytics.tsx, src/domain/settings/personal-information/usage-insights/usage-insights-modal.tsx, src/services/analytics.ts
**What**
- Enables gathering analytics in a development environment.
- Re-adds InputField for user email in preference modal.
Resolves CORE-769
=> fix: analytics in dev

src/domain/sales-channels/pages/details.tsx
**What**
- remove action for deleting an SC if the channel is the default one
---
FIXES CORE-561
=> fix: disallow deletion of the default SC

src/domain/orders/details/create-fulfillment/item-table.tsx
**What**
- Subtract the already fulfilled amount from the fulfillable amount
- filter order items based on fulfilll-ability
Fixes CORE-437
=> Fix: Quantities in fulfillment item table

src/services/api.js, src/services/request.js
**What**
- Fixes broken image upload.
=> hotfix: Fix broken image upload

src/components/templates/discount-table/use-promotion-columns.tsx
Lines 24-27 are unchanged, eslint freakes out there.
Table molecule is unused.
Fixes https://github.com/medusajs/admin/issues/814
=> Always display redemption count in discounts table

package.json, src/domain/settings/taxes/details.tsx, src/domain/settings/taxes/index.tsx, src/domain/settings/taxes/tax-rate-row.tsx, src/domain/settings/taxes/use-tax-rate-columns.tsx, yarn.lock
=> fix: hook up region id to query params in tax settings

src/components/templates/collection-product-table/add-product-table.tsx, src/domain/discounts/new/discount-form/condition-tables/add-condition-tables/products.tsx, src/domain/orders/details/rma-sub-modals/products.tsx, src/domain/settings/taxes/product-selector.tsx, src/domain/settings/taxes/selectable-table.tsx
**What**
- Fixes broken product search for exchanges/claims and tax product conditions
=> fix: exchange product search and tax product search

src/components/fundamentals/status-indicator/index.tsx, src/components/molecules/select/next-select/components/containers.tsx, src/components/molecules/select/next-select/components/index.ts, src/components/molecules/select/next-select/components/menu.tsx, src/components/molecules/select/next-select/module-augmentation.ts, src/components/templates/customer-orders-table/index.tsx, src/components/templates/transfer-orders-modal/index.tsx, src/domain/orders/details/index.tsx, src/domain/orders/details/templates/display-total.tsx, src/domain/orders/details/templates/fulfillment-status.tsx, src/domain/orders/details/templates/payment-status.tsx
**What**
- Implement transfer order modal
minor changes
- change dot color of status indicator danger dot
- make disabled selects text greyed out to indicate they are disabled
- add truncate prop for select options to optionally truncate text
Fixes CORE-888
=> Feat(admin): Transfer order ownership between customers

src/components/molecules/timeline-events/order-edit/confirmed.tsx
**What**
- fix the "Order accepted" timeline event
- fix hooks conditional rendering and unnecessary requests
---
FIXES CORE-875
=> fix: OE "accepted" event

src/components/fundamentals/icons/u-turn-icon.tsx, src/components/molecules/customers-groups-summary/index.tsx, src/components/molecules/input/index.tsx, src/components/molecules/modal/side-modal.tsx, src/components/molecules/sales-channels-summary/index.tsx, src/domain/orders/new/new-order.tsx, src/domain/publishable-api-keys/modals/add-sales-channels.tsx, src/domain/publishable-api-keys/modals/details.tsx, src/domain/publishable-api-keys/modals/manage-sales-channels.tsx, src/domain/publishable-api-keys/pages/index.tsx, src/domain/publishable-api-keys/tables/publishable-api-keys-table.tsx, src/domain/publishable-api-keys/tables/sales-channels-table.tsx, src/domain/sales-channels/tables/product.tsx
**What**
- add support for sales channels management:
- allow adding sales channels while creating a PK
- edit sales channels for an existing PK
**Note**
- depends on https://github.com/medusajs/medusa/pull/2810
---
RESOLVES CORE-822
=> feat: PK sales channels management

src/components/templates/order-table/index.tsx, src/domain/orders/index.tsx, src/domain/orders/utils.ts
**What**
- pass filters selected in the order table header as arguments to export orders batch job
RESOLVES CORE-581
=> feat: pass order filters to export orders batch job

src/domain/settings/regions/components/shipping-option-form/index.tsx
**What**
- Fixes a bug preventing users from creating calculated shipping options.
Fixes CORE-1053
=> fix: ensure onChange is called in `price_type` controller

src/components/molecules/timeline-events/order-edit/payment-required.tsx
**What**
- fix the condition for displaying the "payment required" timeline event
---
FIXES CORE-1081
=> fix: payment required on returns

src/components/atoms/copy-to-clipboard/index.tsx, src/components/molecules/timeline-events/claim-event/index.tsx, src/domain/orders/components/items-to-receive-form/use-items-to-receive-columns.tsx, src/domain/orders/components/items-to-return-form/index.tsx, src/domain/orders/components/items-to-return-form/use-return-item-columns.tsx, src/domain/orders/components/items-to-send-form/use-additional-items-columns.tsx, src/domain/orders/components/rma-summaries/claim-summary.tsx, src/domain/orders/components/rma-summaries/summary-line-item.tsx, src/domain/orders/details/utils/get-default-values.ts
**What**
- Adds SKUs to all table views in claims flow
=> hotfix: add skus to claim tables

src/domain/orders/new/components/summary.tsx
Solves [#3332](https://github.com/medusajs/medusa/issues/3332). 
Fine to await merging this one @kasperkristensen - up to you. Just thought I'd open it to have it ready for either decisions.
=> fix: Discount in DraftOrder create flow
